### ISSUE TITLE
Error at startup with NVDA 2023.3.1

### ISSUE THREAD

**Issue by CyrilleB79** [NSoiffer/MathCAT#268]
### Issue
Following error in log at startup
```
ERROR - globalPluginHandler.listPlugins (15:48:10.747) - MainThread (14516):
Error importing global plugin MathCAT
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\MathCAT\globalPlugins\MathCAT\__init__.py", line 19, in <module>
    from .MathCAT import MathCAT
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\MathCAT\globalPlugins\MathCAT\MathCAT.py", line 26, in <module>
    from . import libmathcat        # type: ignore
ImportError: DLL load failed: La procédure spécifiée est introuvable.
```

### Context
* NVDA 2023.3.1 (temporary version from installer)
* MathCAT version: 0.5.6

**Comment by NSoiffer** [comment]
This seems to be resolved. Please re-open if you are still seeing the problem.
